<?xml version="1.0" encoding="utf-8" ?>\n<!DOCTYPE document [\n  <!ELEMENT document (author,title,body)>\n  <!ELEMENT author (#PCDATA)>\n  <!ELEMENT title (#PCDATA)>\n  <!ELEMENT body (br*,hr*,img*,table*)>\n  <!ELEMENT br EMPTY>\n  <!ELEMENT hr EMPTY>\n  <!ELEMENT img EMPTY>\n  <!ELEMENT table (tr+)>\n  <!ELEMENT tr (td+)>\n  <!ELEMENT td (#PCDATA|br|hr|img|table)*>\n\n  <!-- hr element -->\n  <!ATTLIST hr width CDATA "0">\n\n  <!-- img element -->\n  <!ATTLIST img height CDATA "0">\n  <!ATTLIST img src CDATA #REQUIRED>\n  <!ATTLIST img width CDATA "0">\n\n  <!-- td element -->\n  <!ATTLIST td width CDATA "0">\n]>\n\n<document>\n  <author>My Author</author>\n  <title>My Title Test</title>\n  <body>\n    <hr />\n    <table>\n      <tr>\n        <td>Would like elements here <br /> <img src="image.jpg" /> <table><tr><td>Nested table</td></tr></table></td>\n      </tr>\n    </table>\n  </body>\n</document>