<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE names [\n    <!ELEMENT names (name+)>\n    <!ELEMENT name (text, creator+, history)>\n    <!ELEMENT text (#PCDATA)>\n    <!ELEMENT creator (#PCDATA)>\n    <!ELEMENT history (#PCDATA)>\n    <!ENTITY lost "Lost in the depths of time.">\n    <!ENTITY eacute "Ã©">\n]>\n<names>\n    <name>\n        <text>Pep&eacute;</text>\n        <creator>&lost;</creator>\n        <history>&lost;</history>\n    </name>\n    <name>\n        <text>Charles</text>\n        <creator>James</creator>\n        <history>&lost;</history>\n    </name>\n</names>